name: WebdriverIO Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "\U0001F4E5 Checkout code"
        uses: actions/checkout@v3
      - name: "\U0001F7E2 Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "\U0001F4E6 Install dependencies"
        run: npm install
      - name: "\U0001F527 Build TypeScript"
        run: npm run build
      - name: "\U0001F9EA Run WebdriverIO Tests"
        run: npm test
